build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_USERNAME: "conan"
    CONAN_LOGIN_USERNAME: "conanbot"
    CONAN_CHANNEL: "stable"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools --upgrade
  - conan user # It creates the conan data directory

test_script:
  - python build.py
